name: Generate Snake Animation

permissions:
  contents: write

on:
  schedule:
    # Roda à meia-noite (UTC) todos os dias
    - cron: "0 0 * * *"
  
  # Permite que você rode manualmente pela aba Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do seu repositório
      - uses: actions/checkout@v3

      # Gera a animação da cobrinha (versão mais recente)
      - uses: Platane/snk@v3
        with:
          # Pega dinamicamente o seu nome de usuário do GitHub
          github_user_name: ${{ github.repository_owner }}
          
          # Define os arquivos de saída, agora com os eixos de dia/mês
          outputs: |
            dist/github-contribution-grid-snake.svg?&show_axis=true
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&show_axis=true

      # Publica os arquivos gerados no branch 'output'
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
